RedCloudWork/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using RedCloudWork.Areas.HelpPage.ModelDescriptions;
using RedCloudWork.Areas.HelpPage.Models;

namespace RedCloudWork.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

RedCloudWork/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using RedCloudWork.Domian;
using RedCloudWork.Models;

namespace RedCloudWork.Controllers
{
    public class BillsController : Controller
    {

        #region 辅助方法
        protected List<Bills> GetBillsByExecl(string fileName, string name)
        {
            var table = ComMethod.GetDataTableByExecl(fileName);

            //var list = table.GetModelByDataTable<Bills>();
            var list = GeListByDt(table, name);

            return list;
        }
        protected List<Bills> GeListByDt(DataTable dt, string name)
        {
            var list = new List<Bills>();

            try
            {
                var productRepository = ComMethod.GetRepository<Products>();
                var saleManRepository = ComMethod.GetRepository<Salesman>();
                var merchantRepository = ComMethod.GetRepository<Merchants>();
                var billsRepository = ComMethod.GetRepository<Bills>();

                foreach (DataRow row in dt.Rows)
                {
                    var productName = row["产品"].ToString();
                    var merchantNo = row["商户编号"].ToString();
                    var product = productRepository.Table.FirstOrDefault(p => p.Name == productName);
                    var saleMan = saleManRepository.Table.FirstOrDefault(p => p.Name == name);
                    var merchant = merchantRepository.Table.FirstOrDefault(p => p.MerchantNo == merchantNo);

                    if (product == null)
                    {
                        product = new Products() { Name = productName };
                        productRepository.Insert(product);
                        product = productRepository.Table.FirstOrDefault(p => p.Name == productName);
                    }
                    if (saleMan == null)
                    {
                        saleMan = new Salesman() { Name = name };
                        saleManRepository.Insert(saleMan);
                        saleMan = saleManRepository.Table.FirstOrDefault(p => p.Name == name);
                    }
                    if (merchant == null)
                    {
                        merchant = new Merchants()
                        {
                            MerchantNo = merchantNo,
                            Name = row["商户"].ToString()
                        };
                        merchantRepository.Insert(merchant);
                        merchant = merchantRepository.Table.FirstOrDefault(p => p.MerchantNo == merchantNo);
                    }


                    var model = new Bills
                    {
                        Product = product,
                        ProductId = product.Id,
                        ChargeSource = row["计费来源"].ToString(),
                        Salesman = saleMan,
                        SalesmanId = saleMan.Id,
                        ServiceRequestNo = row["业务请求编号"].ToString(),
                        Merchant = merchant,
                        MerchantId = merchant.Id,
                        Amount = decimal.Parse(row["计费金额"].ToString()),
                        TradingTime = DateTime.Parse(row["交易时间"].ToString().ComTime()),
                        CompletionTime = DateTime.Parse(row["完成时间"].ToString().ComTime()),
                        ProductExpense = decimal.Parse(row["产品费用"].ToString()),
                        CompleteState = row["状态"].ToString() == "已完成"
                    };

                    billsRepository.Insert(model);
                }
            }
            catch (Exception ex)
            {
                //写入日志
            }
            return list;

        }
        #endregion

        // GET: Bills
        public ActionResult AddBills()
        {
            var myContext = new MyDbcontext();
            var list = (from item in myContext.Saleswoman
                        select new SelectListItem()
                        {
                            Text = item.Name,
                            Value = item.Name
                        }).ToList();
            ViewBag.Salses = list;

            return View();
        }
        [HttpPost]
        public JsonResult AddBills(string name, HttpPostedFileBase file)
        {
            if (Request.Files[0] != null)
            {
                var fileName = Path.Combine(Request.MapPath("~/Upload"), DateTime.Now.ToString("yyyyMMddHHmmss") + Path.GetFileName(Request.Files[0].FileName));
                try
                {
                    file.SaveAs(fileName);
                    var list = GetBillsByExecl(fileName, name);

                }
                catch (Exception ex)
                {
                    return Json(new { state = "no" });
                }
            }

            var result = new { state = "ok" };
            return Json(result);
        }


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }

        [HttpPost]
        public JsonResult SelectBills()
        {
            var request = Request;
            var billsRepository = ComMethod.GetRepository<Bills>();
            var dataModel = new DataTablesModel(Request);

            var query =
                billsRepository.Table;
            var allCount = query.Count();

            var seachValue = dataModel.Search.Value;
            if (seachValue != "")
            {
                query = query.Where(x => x.Salesman.Name.Contains(seachValue) || x.Product.Name.Contains(seachValue) || x.Merchant.Name.Contains(seachValue));
                if (seachValue == "完成")
                {
                    query = query.Where(x => x.CompleteState);
                }
            }
            var count = query.Count();
            var sumAmout = count > 0 ? query.Sum(x => x.Amount) : 0;
            var sumExpense = count > 0 ? query.Sum(x => x.ProductExpense) : 0;

            query = query.OrderBy(x => x.TradingTime).Skip(dataModel.Start).Take(dataModel.Length);

            var pageData = (from item in query
                            select new
                            {
                                saleName = item.Salesman.Name,
                                merchantName = item.Merchant.Name,
                                productName = item.Product.Name,
                                requestNo = item.ServiceRequestNo,
                                amount = item.Amount,
                                completedTime = item.CompletionTime,
                                completeState = item.CompleteState,
                                productExpense = item.ProductExpense,
                            }).ToList();

            var restult = new { data = pageData, recordsTotal = allCount, recordsFiltered = count, sumAmout = sumAmout, sumExpense = sumExpense };

            return Json(restult);
        }

        //public ActionResult ExportExcel()
        //{

        //}

    }
}

RedCloudWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RedCloudWork/Views/Shared/_LayoutH.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <title>红云同学专属 - 主页</title>
    <meta name="keywords" content="红云同学专属工作平台">
    <meta name="description" content="红云同学专属，方便工作，后续有更多功能">
    <!--[if lt IE 8]>
    <script>
        alert('已不支持IE6-8，请使用谷歌、火狐等浏览器\n或360、QQ等国产浏览器的极速模式浏览本页面！');
    </script>
    <![endif]-->
    @*<link href="/content/H/bootstrap.min.css?v=3.4.0" rel="stylesheet">*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="/content/H/font-awesome.min.css?v=4.3.0" rel="stylesheet">
    <link href="/content/H/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">
    <link href="/content/H/animate.min.css" rel="stylesheet">
    <link href="/content/H/style.min.css?v=2.2.0" rel="stylesheet">
    @RenderSection("styles",false)
</head>
<body class="fixed-sidebar full-height-layout gray-bg">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close">
                <i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element text-center">
                            <span ><img alt="image" class="img-circle" src="/Images/psu.jpg" /></span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear text-center">
                                    <span class="block m-t-xs"><strong class="font-bold">Hongyun-Yang</strong></span>
                                    <span class="text-muted text-xs block">超级管理员<b class="caret"></b></span>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li>
                                    <a class="J_menuItem" href="#">暂未开发</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="login.html">安全退出</a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            H+
                        </div>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Home")">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">主页</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="@Url.Action("AddBills","Bills")" data-index="0">数据导入</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="@Url.Action("Index","bills")">账单查询</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="index_v3.html">账单图标查询</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="index_v4.html">未完待续</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            @RenderBody()
            <div class="footer fixed">
              
                   2015.11.22 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;踏雪无痕
              
            </div>
        </div>
        <!--右侧部分结束-->

    </div>
    <script id="welcome-template" type="text/x-handlebars-template">
        
    </script>
    <!-- Mainly scripts -->
    <script src="/scripts/h/jquery-2.1.1.min.js"></script>
    <script src="/scripts/h/bootstrap.min.js?v=3.4.0"></script>
    <script src="/scripts/h/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/scripts/h/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Flot -->
    <script src="/scripts/h/plugins/flot/jquery.flot.js"></script>
    <script src="/scripts/h/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="/scripts/h/plugins/flot/jquery.flot.spline.js"></script>
    <script src="/scripts/h/plugins/flot/jquery.flot.resize.js"></script>
    <script src="/scripts/h/plugins/flot/jquery.flot.pie.js"></script>
    <script src="/scripts/h/plugins/flot/jquery.flot.symbol.js"></script>
    <script src="/scripts/h/plugins/flot/curvedLines.js"></script>

    <!-- Peity -->
    <script src="/scripts/h/plugins/peity/jquery.peity.min.js"></script>
    <script src="/scripts/h/demo/peity-demo.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="/scripts/h/hplus.js?v=2.2.0"></script>
    <script src="/scripts/h/plugins/pace/pace.min.js"></script>

    <!-- jQuery UI -->
    <script src="/scripts/h/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Jvectormap -->
    <script src="/scripts/h/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/scripts/h/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

    <!-- EayPIE -->
    <script src="/scripts/h/plugins/easypiechart/jquery.easypiechart.js"></script>

    <!-- Sparkline -->
    <script src="/scripts/h/plugins/sparkline/jquery.sparkline.min.js"></script>

    <!-- Sparkline demo data  -->
    <script src="/scripts/h/demo/sparkline-demo.min.js"></script>

    <script>
        $(document).ready(function () {
            $('.chart').easyPieChart({
                barColor: '#f8ac59',
                //                scaleColor: false,
                scaleLength: 5,
                lineWidth: 4,
                size: 80
            });

            $('.chart2').easyPieChart({
                barColor: '#1c84c6',
                //                scaleColor: false,
                scaleLength: 5,
                lineWidth: 4,
                size: 80
            });

            var d1 = [
                [1262304000000, 1],
                [1264982400000, 100],
                [1267401600000, 1],
                [1270080000000, 200],
                [1272672000000, 1],
                [1275350400000, 100],
                [1277942400000, 1],
                [1280620800000, 300]
            ];
            var d2 = [
                [1262304000000, 100],
                [1264982400000, 1],
                [1267401600000, 150],
                [1270080000000, 1],
                [1272672000000, 230],
                [1275350400000, 1],
                [1277942400000, 150],
                [1280620800000, 10]
            ];

            var data3 = [
                {
                    label: "Data 1",
                    data: d1,
                    color: '#23c6c8'
                },
                {
                    label: "Data 2",
                    data: d2,
                    color: '#1ab394'
                }
            ];
            //$.plot($("#flot-chart3"), data3, {
            //    xaxis: {
            //        tickDecimals: 0
            //    },
            //    series: {
            //        lines: {
            //            show: true,
            //            fill: true,
            //            fillColor: {
            //                colors: [{
            //                    opacity: 1
            //                }, {
            //                    opacity: 1
            //                }]
            //            },
            //        },
            //        curvedLines: {
            //            active: true,
            //            fit: true,
            //            apply: true
            //        },
            //        points: {
            //            width: 0.1,
            //            show: false
            //        },
            //    },
            //    grid: {
            //        show: false,
            //        borderWidth: 0
            //    },
            //    legend: {
            //        show: false,
            //    }
            //});


            var mapData = {
                "US": 298,
                "SA": 200,
                "DE": 220,
                "FR": 540,
                "CN": 120,
                "AU": 760,
                "BR": 550,
                "IN": 200,
                "GB": 120,
            };

            $('#world-map').vectorMap({
                map: 'world_mill_en',
                backgroundColor: "transparent",
                regionStyle: {
                    initial: {
                        fill: '#e4e4e4',
                        "fill-opacity": 0.9,
                        stroke: 'none',
                        "stroke-width": 0,
                        "stroke-opacity": 0
                    }
                },

                series: {
                    regions: [{
                        values: mapData,
                        scale: ["#1ab394", "#22d6b1"],
                        normalizeFunction: 'polynomial'
                    }]
                },
            });
        });
    </script>

    @RenderSection("scripts",false)
</body>
</html>